### ISSUE TITLE
Botの詳細

### ISSUE THREAD

**Issue by arsley** [arsley/fidop#1]
Botの詳細を適当に決めたい (全部満たされなくとも可)。

- 名前
- 画像
- 説明
- その他何でも

**Comment by tj16kimura** [comment]
Hydraみたいなかっこいい名前がいいなぁ

**Comment by arsley** [comment]
名前 : Fidop (Fukai Iyashi Doubutsu Ohirune Package, /fài-dop/)

**Comment by skyloken** [comment]
👍

**Comment by tj16kimura** [comment]
:lgtm:

**Comment by skyloken** [comment]
- `/fidop` : **FIDOP**に準拠した文字列を生成する
  - ex) 深い癒し動物お昼寝パッケージ6

**Comment by arsley** [comment]
> * `/fidop` : **FIDOP**に準拠した文字列を生成する
>       
>       * ex) 深い癒し動物お昼寝パッケージ6

#4
