### ISSUE TITLE
Discordにリポジトリに関する通知を送る

### ISSUE THREAD

**Issue by skyloken** [arsley/fidop#6]
- 開発進んだりしたらdiscordで知りたい
- webhookでいけるらしい
  - https://mekurun.com/tips/discord-github/
- リポジトリ管理者たのみます @arsley

**Comment by tj16kimura** [comment]
SlackだとアプリあるけどそういうのDiscordないんかな
或いは開発用にSlackを作るか

**Comment by skyloken** [comment]
どうやらないらしい
たしかに開発ならslackのが向いてるかもな

**Comment by tj16kimura** [comment]
開発せん人もオルシ、ゲームと分けるという意味でもSlackあっても良さそう I think.

**Comment by arsley** [comment]
お察しの通りDiscordとGitHub通知は若干相性が悪いので Slack でいいと思います (game との差別化もできるしなお good)。

**Comment by arsley** [comment]
slackを作ったのでLGTM close
